### ISSUE TITLE
out of the box installation fails 

### ISSUE THREAD

**Issue by krtschmr** [afomera/richer_text#16]
- brand new rails 8.0-alpha project
- create model `Post`
- add `richer_text`
- create simple view
- `rails s`

result:

![image](https://github.com/user-attachments/assets/e481de05-5172-43b4-8f95-0034d4f498f2)

demo source: https://github.com/krtschmr/richert_text_fail_demo

it's been a while that i've setup a new rails app, i'm just confused what went wrong?

**Comment by mskim** [comment]
rails8.0-beta.
Error: Failed to find '@afomera/richer-text/dist/css/richer-text.css'
16:10:18 css.1  |   in [
16:10:18 css.1  |     /Users/mskim/Development/rails8/book/app/assets/stylesheets
16:10:18 css.1  |   ]
16:10:18 css.1  |     at /snapshot/tailwindcss/node_modules/postcss-import/lib/resolve-id.js:35:13
16:10:18 css.1  |     at async LazyResult.runAsync (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:261:11)
16:10:18 css.1  |     at async Object.watch (/snapshot/tailwindcss/lib/cli/build/plugin.js:370:13)
16:10:18 css.1  |     at async build (/snapshot/tailwindcss/lib/cli/build/index.js:47:9)
16:10:37 web.1

**Comment by afomera** [comment]
Ah this must be a propshaft related bug tbh. Will look into it!

**Comment by mskim** [comment]
아주 수고가 많으십니다. 좋은 프로젝트를 개발 해주셔서 감사합니다.

**Comment by afomera** [comment]
This is now fixed in 0.18.0 of the ruby gem!
